### ISSUE TITLE
Update Manual for 3.6.0 Release

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#155]
Complementary issue just to help tracking entries necessary for a 3.6.0 release

**TODO:**

- [x] Rewrite [Default Setup](https://github.com/adventuregamestudio/ags-manual/wiki/DefaultSetup) as some options already don't match winsetup, and more may follow in further versions 

**DONE:**
- [x] Obsolete licensing #198
- [x] add eKeyMod #176
- [x] Android Build #194  
- [x] AudioChannel update #162
- [x] AudioClip PlayOnChannel #166
- [x] Button update #185
- [x] Character AnimationVolume #191
- [x] Character.IdleDelay #163
- [x] Control Transparency #187
- [x] Credits #168   
- [x] Debug update #178
- [x] dialog_options_key_press update #175
- [x] DrawingSurface update #154
- [x] Events Order #190
- [x] Game.BlockingWaitSkipped #153
- [x] Logging #117 
- [x] Mask Drawing #116
- [x] Multiple Speechvox #173
- [x] Object update #152
- [x] on_key_press update #174
- [x] Overlay new properties #165
- [x] Overlay Resize #186 
- [x] Packaging and "$DATA$"  token #164
- [x] Preferences docs #183 
- [x] Room.Exists #151
- [x] Room Overlays #192
- [x] Runtime update #132
- [x] Sound Formats #180
- [x] Speech Overlays #150
- [x] String utf-8 #177
- [x] Upgrading to 3.6.0 #158
- [x] Wait & Skip #118
- [x] acsprset.spr recreation #188
- [x] Unicode mode #179
- [x] Translation with UTF-8 #167  

*Reminder:* add the following on script API added (new entries), on bottom before *see also:*.

```
*Compatibility:* Supported by **AGS 3.6.0** and later versions.
```

**Comment by ericoporto** [comment]
Small reminder, need to create tasks specific to new audio functions and also a new task specific to writing the "Upgrading to 3.6.0 version".

**Comment by ivan-mogilko** [comment]
Pushed a preliminary changelog for the 3.6.0, may be used for the quick reference too:
https://github.com/adventuregamestudio/ags/commit/ea4356d899bb17e2e3e067478a72838b1b8f3ac0

**Comment by ivan-mogilko** [comment]
Only "Default Setup" remaining.

**Comment by ivan-mogilko** [comment]
I think it's done, anything missing may be added separately anytime.
