### ISSUE TITLE
[3.6.1] prepare for 3.6.1 release

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#220]
- [x] Document Button's and Label's special text values #239 
- [x] Interaction callbacks: new parameters (note they are optional and may be skipped, similar to on_key_press new arg) #230 
- [x] Changes to plugin API: ResolveFilePath; also mention that GetPathToFileInCompiledFolder is now deprecated and users should use ResolveFilePath instead.
- [x] Add miniz on licensing #240
- [x] IAGSStream added to plugin API. #241
- [x] Script API: document ScriptName and GetByName #229 
- [x] General settings: Scale Character sprite offsets.
- [x] Update config options (cache settings);
- [x] Mention new options in Default Setup.
- [x] Room Editor: "After fade-out" event #235
- [x] Document Log Panel #219 
- [x] Room Editor: improved controls (panning, zoom to cursor, way to call context menu) #233
- [x] Update available options in Winsetup #232
- [x] Script API: document File.ResolvePath and File.Path #231
- [x] Script API: additional formatting options #225
- [x] Script API: Game.ResetDoOnceOnly #226 
- [x] Object.AnimationVolume, works same as Character.AnimationVolume added in 3.6.0 #227
- [x] Script API: eEventLeaveRoomAfterFadeout, eEventGameSaved events #228

**Comment by ericoporto** [comment]
I am creating separate issues for each thing as I work these so any issue that requires some change or something, it can be talked there, and if the issue is closed it can be reopened, this is just to make it easier to organize and track changes in the wiki, matching with their respective tasks.

**Comment by ericoporto** [comment]
> Mention new options in Default Setup.

This category is here: https://github.com/adventuregamestudio/ags-manual/wiki/DefaultSetup

I am a bit at a trouble trying to figure this out, in theory the only changes here from 3.6.0 are the below two entries in the performance category.

- **Texture cache size (in megabytes)**
  The limit for runtime texture cache. The cache is used to keep textures loaded in VRAM (your graphics card memory), and improves performance.
- **Sound cache size (in megabytes)**
  The limit for runtime sound cache. The cache is used to keep small sound clips loaded (typically the ones less than 1 MB each). Bigger cache means less loading of the same clips, such as frame-linked sounds, and improves performance.

But there's almost nothing written in this topic itself and some options that are there are in the config file docs and not in the winsetup specifically. I am a bit unsure in how to update and if some things that are added in 3.6.0 that we never wrote should be mentioned there - like rotation which is relevant on mobile.

**Comment by ivan-mogilko** [comment]
I guess it's best to recreate a topic into something similar to General Settings. Options in Default Setup no longer match winsetup window.

**Comment by ericoporto** [comment]
OK, I will instead rewrite that entry adding all options.

I noticed we never finished #155 so I will look into closing that one too.

**Comment by ivan-mogilko** [comment]
> I guess it's best to recreate a topic into something similar to General Settings. Options in Default Setup no longer match winsetup window.

I have not realized earlier, but this had to be done for 3.6.0 already, as 3.6.0 included options that are not present in winsetup. Besides "rotation" there's also "touch emulation", and maybe something else which i missed.

**Comment by ivan-mogilko** [comment]
@ericoporto I went ahead and rewrote "Default Setup", but only for 3.6.0 because i'd like to release a 3.6.0 patch soon.
3.6.1 options are still missing there.

**Comment by ericoporto** [comment]
Is there anything else missing in documentation for 3.6.1? Maybe some later API addition was forgotten.

**Comment by ivan-mogilko** [comment]
I ran along the changelog from RC recently, and I think everything is in place.

**Comment by ericoporto** [comment]
We don't need an Upgrading to 3.6.1 topic, right? We don't always write one of those topics but I wasn't sure if one for 3.6.1 was necessary or not.

**Comment by ivan-mogilko** [comment]
> We don't need an Upgrading to 3.6.1 topic, right? We don't always write one of those topics but I wasn't sure if one for 3.6.1 was necessary or not.

I wrote one: https://github.com/adventuregamestudio/ags-manual/wiki/UpgradeTo361

**Comment by ivan-mogilko** [comment]
So, i think that the main 3.6.1 list is covered.
