### ISSUE TITLE
Update for 3.6.2

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#254]
List of things that has to be documented for 3.6.2 update:

**For the Editor help:**
- [x] - Script module selection for linked events. I suppose that this has to be added to Tutorials with the new screenshots which display the module selection where it is available (e.g. Characters). EDIT: sort of done, mentioned this ability in few places, but it would require a larger tutorial change to have it mentioned properly.
- [x] - New naming rule for the voice clips, updated info in "Voice speech" article.
- [x] - In General Settings added "Use old-style voice clip naming rule".
- [CANCEL] "WrapText", "TextPaddingHorizontal", "TextPaddingVertical" properties to GUI Button. EDIT: apparently there's no real description of gui properties, only very short sections for each gui control.
- [CANCEL] - Mention "Null Font" in GUI article? EDIT: idk where to add this
- [CANCEL] Removed obsolete "Copy walkable area mask to regions" command from the Room editor. -- Was this toolbutton mentioned anywhere? EDIT: was not mentioned anywhere.
- [x] - Added "/maketemplate" command-line option.

**Script API:**
- [x] - Length for Dynamic Arrays </br> #281
- [x] - Expanded `on_mouse_click` callback, now supports two more parameters: click x,y coordinates. </br> #275
- [x] - Expanded `dialog_options_mouse_click` callback, now it supports click x and y coordinates </br> #276

**Engine Plugin API:**
- [x] - IAGSEngine.Log()
- [x] - CreateDynamicArray, GetDynamicArrayLength, GetDynamicArraySize

**Mention change in behavior (Version compatibility notes?):**
- [x] - Assigning InventoryItem.Graphic will no longer reassign CursorGraphic too even if they were identical previously

**Config and setup program, engine command line:**
- [x] - Added new accessibility config settings in "access" section: "speechskip" and "textskip".
   These let player to override game's skipping style for character speech and text messages
   respectively.
- [x] - Added "max_save" config option in "override" section: this lets to enforce an arbitrary number
   of saves displayed in a standard save/restore dialogs in game.
- [x] - Added "--no-plugins" command-line argument that denies loading any plugins;
   also added respective config option "noplugins" in "override" section.

**DONE:**

**Mention change in behavior (Version compatibility notes?):**
- [x] - Calling DeleteSaveSlot() on a slot within 0-50 range will no longer secretly move a save with the topmost number (within the same range) to fill the emptied slot.</br> #268

**Script API:**
- [x] - on_event: eEventDialogStart/Stop, eEventDialogRun, eEventDialogOptionsOpen/Close </br> #256
- [x] - File.Copy() and File.Rename(). </br> #262
- [x] - File.GetFileTime() , returns modification time. </br> #262
- [x] - System.GetEngineInteger() and System.GetEngineString() </br> #260
- [x] - option OPT_SAVEGAMESCREENSHOTLAYER sets render layers in game save screenshot </br> #261 
- [x] - Added CopySaveSlot() and MoveSaveSlot() </br> #268
- [x] - "layers" parameter to DynamicSprite.CreateFromScreenShot(), </br> #258
- [x] - Added Game.GetSaveSlotTime() that returns a time this save slot was last written. </br> #271
- [x] - ListBox FillSaveGameList and FillSaveGameList update </br> #266 
- [x] - FileSortStyle, SaveGameSortStyle and SortDirection enum </br> #259
- [x] - EngineValueID enum. </br> #259
- [x] - RenderLayer enum </br> #259
- [x] - eNullFont </br> #259
- [x] - System.DisplayFPS </br> https://github.com/adventuregamestudio/ags-manual/issues/279
- [x] - Added GetTimerPos() that returns timer's position (remaining time), in ticks. </br> #269
- [x] - Character.Following </br> #280 
- [x] - Button.WrapText, TextPaddingHorizontal, TextPaddingVertical. </br> #263 
- [x] - Label.TextAlignment has now type Alignment, rather than HorizontalAlignment </br> #273
- [x] - Added optional "sprite" parameter to SaveGameSlot(), that lets to pass a number of an arbitrary sprite to write into this save instead of a standard "screenshot". </br> #274
- [x] - Added DateTime.CreateFromDate() and CreateFromRawTime(). </br> #272
- [x] - Character.TurnWhenFacing property. </br> #257
- [x] - Character.MoveStraight() complementing WalkStraight(). </br> #257
- [x] - static Dialog.CurrentDialog and non-static ExecutedOption and AreOptionsDisplayed properties </br> #264
- [x] - RestoreGameDialog() and SaveGameDialog() </br> #267
- [x] - Added Overlay.SetPosition() and SetSize() </br> #270 
- [x] - Speech.SpeakingCharacter </br> #265 
- [x] - Character.Speaking returns true when a speech is playing even if the character has no speech view </br> #257

**Comment by ericoporto** [comment]
Create an individual issue for a bunch of things - not all yet, but I guess it's best to work on clearing up the added stuff and later return to the remaining stuff. 

Going through the script API specifically, it's mostly lots things that are quite useful in the day-to-day agsing, helpful things that makes life easier with the already existing systems in ags.

**Comment by ericoporto** [comment]
I added a bunch of things more to the manual. Need to recheck if something is missing in the above list and also create any missing issues.

I believe a Upgrading to 3.6.2 page would be useful too to pick the highlights of this version to add too.

**Comment by ivan-mogilko** [comment]
Wrote an initial variant of "Upgrade to 3.6.2": https://github.com/adventuregamestudio/ags-manual/wiki/UpgradeTo362
explained loading old saves in summary, since that's the most complicated thing in this update.

**Comment by ericoporto** [comment]
That is a great writing! I thought about a few things that would be just small notes

- the new voice clip naming rules
- the event handlers being supported in any script module
- editor warning about probably "unlinked" functions and warning about handlers that are "linked" in editor but not available in script (perhaps in the same section as above?)
- maybe also the Length property in Dynamic Arrays?

**Comment by ivan-mogilko** [comment]
Added few things for now; but i think that we need to add links to detailed articles when these are ready.

**Comment by ivan-mogilko** [comment]
Added a number of things recently that were not in original list:
* System.GetEngineInteger and GetEngineString
* File.GetFiles
* Game.GetSaveSlots()
* Game.ScanSaveSlots
* validate_restored_save, in a whole new page here: https://github.com/adventuregamestudio/ags-manual/wiki/ValidateRestoredSave

**Comment by ericoporto** [comment]
Thanks, I did a quick check of those and fixed links and a few small format things and put in a release, to also update the web manual.

**Comment by ivan-mogilko** [comment]
Added a page for RestoredSaveInfo:
https://github.com/adventuregamestudio/ags-manual/wiki/RestoredSaveInfo

While writing it, i realized that it may make sense to also add "ModuleNames[]" to it, if someone wants to check which of these are present in case of smaller number (since modules are allowed to be loaded in any order now).

**Comment by ivan-mogilko** [comment]
Closed remaining items.
